name: 'Build and Push Container on AWS ECR'
description: 'Build and Push Container on AWS ECR'
inputs:
  aws-region:
    description: 'AWS Region, e.g. us-east-2'
    required: true
  role-to-assume:
    description: >-
      Use the provided credentials to assume an IAM role and configure the Actions
      environment with the assumed role credentials rather than with the provided
      credentials
    required: true
  docker-registry:
    description: 'AWS ECR Registry'
    required: true
  dockerfile-path:
    description: 'The Dockerfile path'
    default: '.'
    required: false    
  docker-build-extra-args:
    description: 'Extra arguments for docker build'
    default: ''
    required: false
  repository-name:
    description: 'Repository Name '
    default: ''
    required: false    
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: GitHubActionsECR

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: build
      env:
        DOCKER_REGISTRY: ${{ inputs.docker-registry }}
      shell: bash        
      run: |
        if [ -z "${{ inputs.repository-name }}" ]
        then 
              export REPOSITORY_NAME=$GITHUB_REPOSITORY
        else 
              export REPOSITORY_NAME=${{ inputs.repository-name }}
        fi 
        aws ecr describe-repositories --repository-names "${REPOSITORY_NAME}" || aws ecr create-repository --repository-name "${REPOSITORY_NAME}"
        docker pull $DOCKER_REGISTRY/${REPOSITORY_NAME}:latest || true
        docker build ${{ inputs.docker-build-extra-args }} --cache-from $DOCKER_REGISTRY/${REPOSITORY_NAME}:latest -t $DOCKER_REGISTRY/${REPOSITORY_NAME}:$GITHUB_SHA ${{ inputs.dockerfile-path }}
        docker tag "$DOCKER_REGISTRY/${REPOSITORY_NAME}:$GITHUB_SHA" $DOCKER_REGISTRY/${REPOSITORY_NAME}:latest
        docker push "$DOCKER_REGISTRY/${REPOSITORY_NAME}" -a      
